name: hadiths
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  salomon_bottom_bar: ^3.3.2
  flutter_html: ^3.0.0-beta.2
  scrollable_positioned_list: ^0.3.8
  sqflite: ^2.3.3+1
  path: ^1.8.3
  share_plus: ^9.0.0
  clipboard: ^0.1.3
  provider: ^6.1.2
  wakelock_plus: ^1.2.5
  hive_flutter: ^2.0.0-dev

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/databases/
    - assets/fonts/

  fonts:
    - family: Heuristica
      fonts:
        - asset: assets/fonts/heuristica.ttf
    - family: Uthmanic
      fonts:
        - asset: assets/fonts/uthmanic.ttf
